version: 2
updates:
- package-ecosystem: gradle
  directory: "/java"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.netty:netty-transport-native-kqueue
    versions:
    - 4.1.56.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-transport-native-epoll
    versions:
    - 4.1.56.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-all
    versions:
    - 4.1.56.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.30
    - 1.4.31
  - dependency-name: org.fusesource.jansi:jansi
    versions:
    - 2.3.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
- package-ecosystem: nuget
  directory: "/csharp/core"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.Logging
    versions:
    - 5.0.0
- package-ecosystem: nuget
  directory: "/csharp/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: NLog.Extensions.Logging
    versions:
    - 1.7.1
  - dependency-name: NLog
    versions:
    - 4.7.8
