// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface AutoCompletePacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.AutoCompletePacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  java.util.List<com.github.fernthedev.data.LightCandidateData> 
      getCandidateListList();
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  com.github.fernthedev.data.LightCandidateData getCandidateList(int index);
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  int getCandidateListCount();
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  java.util.List<? extends com.github.fernthedev.data.LightCandidateDataOrBuilder> 
      getCandidateListOrBuilderList();
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  com.github.fernthedev.data.LightCandidateDataOrBuilder getCandidateListOrBuilder(
      int index);

  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  java.util.List<java.lang.String>
      getWordsListJsonList();
  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  int getWordsListJsonCount();
  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  java.lang.String getWordsListJson(int index);
  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  com.google.protobuf.ByteString
      getWordsListJsonBytes(int index);
}
