// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface ConnectedPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.ConnectedPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string os = 5;</code>
   */
  java.lang.String getOs();
  /**
   * <code>string os = 5;</code>
   */
  com.google.protobuf.ByteString
      getOsBytes();

  /**
   * <code>string uuid = 6;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 6;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string privateKey = 7;</code>
   */
  java.lang.String getPrivateKey();
  /**
   * <code>string privateKey = 7;</code>
   */
  com.google.protobuf.ByteString
      getPrivateKeyBytes();
}
