// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface MessagePacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.MessagePacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool command = 2;</code>
   */
  boolean getCommand();
}
