// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_MessagePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_MessagePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_AutoCompletePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_AutoCompletePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_ConnectedPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_ConnectedPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_IllegalConnectionPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_IllegalConnectionPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_RequestInfoPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_RequestInfoPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_SelfMessagePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_SelfMessagePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Packet.proto\022\023lightclient.packets\032\024Lig" +
      "htCandidate.proto\032\031google/protobuf/any.p" +
      "roto\"1\n\rMessagePacket\022\017\n\007message\030\001 \001(\t\022\017" +
      "\n\007command\030\002 \001(\010\"k\n\022AutoCompletePacket\022>\n" +
      "\rcandidateList\030\002 \003(\0132\'.lightclient.packe" +
      "ts.LightCandidateData\022\025\n\rwordsListJson\030\003" +
      " \003(\t\"M\n\017ConnectedPacket\022\014\n\004name\030\004 \001(\t\022\n\n" +
      "\002os\030\005 \001(\t\022\014\n\004uuid\030\006 \001(\t\022\022\n\nprivateKey\030\007 " +
      "\001(\t\"*\n\027IllegalConnectionPacket\022\017\n\007messag" +
      "e\030\010 \001(\t\"*\n\021RequestInfoPacket\022\025\n\rencrypti" +
      "onKey\030\t \001(\t\"N\n\021SelfMessagePacket\0229\n\013mess" +
      "ageType\030\n \001(\0162$.lightclient.packets.Self" +
      "MessageType*\335\001\n\017SelfMessageType\022\026\n\022FillP" +
      "asswordPacket\020\000\022\036\n\032LostServerConnectionP" +
      "acket\020\001\022\022\n\016RegisterPacket\020\002\022\036\n\032TimedOutR" +
      "egistrationPacket\020\003\022\016\n\nPongPacket\020\004\022\017\n\013P" +
      "ingReceive\020\005\022\016\n\nPingPacket\020\006\022\027\n\023Authenti" +
      "cateMessage\020\007\022\024\n\020DisconnectPacket\020\010B#\n\035c" +
      "om.github.fernthedev.packetsH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.fernthedev.data.LightCandidate.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_lightclient_packets_MessagePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightclient_packets_MessagePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_MessagePacket_descriptor,
        new java.lang.String[] { "Message", "Command", });
    internal_static_lightclient_packets_AutoCompletePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightclient_packets_AutoCompletePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_AutoCompletePacket_descriptor,
        new java.lang.String[] { "CandidateList", "WordsListJson", });
    internal_static_lightclient_packets_ConnectedPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightclient_packets_ConnectedPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_ConnectedPacket_descriptor,
        new java.lang.String[] { "Name", "Os", "Uuid", "PrivateKey", });
    internal_static_lightclient_packets_IllegalConnectionPacket_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lightclient_packets_IllegalConnectionPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_IllegalConnectionPacket_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_lightclient_packets_RequestInfoPacket_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lightclient_packets_RequestInfoPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_RequestInfoPacket_descriptor,
        new java.lang.String[] { "EncryptionKey", });
    internal_static_lightclient_packets_SelfMessagePacket_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lightclient_packets_SelfMessagePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_SelfMessagePacket_descriptor,
        new java.lang.String[] { "MessageType", });
    com.github.fernthedev.data.LightCandidate.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
