// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface RequestInfoPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.RequestInfoPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string encryptionKey = 9;</code>
   */
  java.lang.String getEncryptionKey();
  /**
   * <code>string encryptionKey = 9;</code>
   */
  com.google.protobuf.ByteString
      getEncryptionKeyBytes();
}
