// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

/**
 * Protobuf type {@code lightclient.packets.SelfMessagePacket}
 */
public  final class SelfMessagePacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lightclient.packets.SelfMessagePacket)
    SelfMessagePacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SelfMessagePacket.newBuilder() to construct.
  private SelfMessagePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SelfMessagePacket() {
    messageType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SelfMessagePacket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 80: {
            int rawValue = input.readEnum();

            messageType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.fernthedev.packets.Packet.internal_static_lightclient_packets_SelfMessagePacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.fernthedev.packets.Packet.internal_static_lightclient_packets_SelfMessagePacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.fernthedev.packets.SelfMessagePacket.class, com.github.fernthedev.packets.SelfMessagePacket.Builder.class);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 10;
  private int messageType_;
  /**
   * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
   */
  public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
   */
  public com.github.fernthedev.packets.SelfMessageType getMessageType() {
    @SuppressWarnings("deprecation")
    com.github.fernthedev.packets.SelfMessageType result = com.github.fernthedev.packets.SelfMessageType.valueOf(messageType_);
    return result == null ? com.github.fernthedev.packets.SelfMessageType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != com.github.fernthedev.packets.SelfMessageType.FillPasswordPacket.getNumber()) {
      output.writeEnum(10, messageType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != com.github.fernthedev.packets.SelfMessageType.FillPasswordPacket.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, messageType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.fernthedev.packets.SelfMessagePacket)) {
      return super.equals(obj);
    }
    com.github.fernthedev.packets.SelfMessagePacket other = (com.github.fernthedev.packets.SelfMessagePacket) obj;

    if (messageType_ != other.messageType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.fernthedev.packets.SelfMessagePacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.fernthedev.packets.SelfMessagePacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lightclient.packets.SelfMessagePacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lightclient.packets.SelfMessagePacket)
      com.github.fernthedev.packets.SelfMessagePacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.fernthedev.packets.Packet.internal_static_lightclient_packets_SelfMessagePacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.fernthedev.packets.Packet.internal_static_lightclient_packets_SelfMessagePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.fernthedev.packets.SelfMessagePacket.class, com.github.fernthedev.packets.SelfMessagePacket.Builder.class);
    }

    // Construct using com.github.fernthedev.packets.SelfMessagePacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.fernthedev.packets.Packet.internal_static_lightclient_packets_SelfMessagePacket_descriptor;
    }

    @java.lang.Override
    public com.github.fernthedev.packets.SelfMessagePacket getDefaultInstanceForType() {
      return com.github.fernthedev.packets.SelfMessagePacket.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.fernthedev.packets.SelfMessagePacket build() {
      com.github.fernthedev.packets.SelfMessagePacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.fernthedev.packets.SelfMessagePacket buildPartial() {
      com.github.fernthedev.packets.SelfMessagePacket result = new com.github.fernthedev.packets.SelfMessagePacket(this);
      result.messageType_ = messageType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.fernthedev.packets.SelfMessagePacket) {
        return mergeFrom((com.github.fernthedev.packets.SelfMessagePacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.fernthedev.packets.SelfMessagePacket other) {
      if (other == com.github.fernthedev.packets.SelfMessagePacket.getDefaultInstance()) return this;
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.fernthedev.packets.SelfMessagePacket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.fernthedev.packets.SelfMessagePacket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int messageType_ = 0;
    /**
     * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
     */
    public Builder setMessageTypeValue(int value) {
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
     */
    public com.github.fernthedev.packets.SelfMessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.github.fernthedev.packets.SelfMessageType result = com.github.fernthedev.packets.SelfMessageType.valueOf(messageType_);
      return result == null ? com.github.fernthedev.packets.SelfMessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
     */
    public Builder setMessageType(com.github.fernthedev.packets.SelfMessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lightclient.packets.SelfMessagePacket)
  }

  // @@protoc_insertion_point(class_scope:lightclient.packets.SelfMessagePacket)
  private static final com.github.fernthedev.packets.SelfMessagePacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.fernthedev.packets.SelfMessagePacket();
  }

  public static com.github.fernthedev.packets.SelfMessagePacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SelfMessagePacket>
      PARSER = new com.google.protobuf.AbstractParser<SelfMessagePacket>() {
    @java.lang.Override
    public SelfMessagePacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SelfMessagePacket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SelfMessagePacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SelfMessagePacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.fernthedev.packets.SelfMessagePacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

