// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface SelfMessagePacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.SelfMessagePacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
   */
  int getMessageTypeValue();
  /**
   * <code>.lightclient.packets.SelfMessageType messageType = 10;</code>
   */
  com.github.fernthedev.packets.SelfMessageType getMessageType();
}
