// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightCandidate.proto

package com.github.fernthedev.data;

public final class LightCandidate {
  private LightCandidate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LightCandidateDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lightclient.packets.LightCandidateData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string value = 1;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>required string displ = 2;</code>
     */
    boolean hasDispl();
    /**
     * <code>required string displ = 2;</code>
     */
    java.lang.String getDispl();
    /**
     * <code>required string displ = 2;</code>
     */
    com.google.protobuf.ByteString
        getDisplBytes();

    /**
     * <code>required string group = 3;</code>
     */
    boolean hasGroup();
    /**
     * <code>required string group = 3;</code>
     */
    java.lang.String getGroup();
    /**
     * <code>required string group = 3;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>required string descr = 4;</code>
     */
    boolean hasDescr();
    /**
     * <code>required string descr = 4;</code>
     */
    java.lang.String getDescr();
    /**
     * <code>required string descr = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescrBytes();

    /**
     * <code>required string suffix = 5;</code>
     */
    boolean hasSuffix();
    /**
     * <code>required string suffix = 5;</code>
     */
    java.lang.String getSuffix();
    /**
     * <code>required string suffix = 5;</code>
     */
    com.google.protobuf.ByteString
        getSuffixBytes();

    /**
     * <code>required string key = 6;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 6;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 6;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required bool complete = 7;</code>
     */
    boolean hasComplete();
    /**
     * <code>required bool complete = 7;</code>
     */
    boolean getComplete();
  }
  /**
   * Protobuf type {@code lightclient.packets.LightCandidateData}
   */
  public  static final class LightCandidateData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lightclient.packets.LightCandidateData)
      LightCandidateDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LightCandidateData.newBuilder() to construct.
    private LightCandidateData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LightCandidateData() {
      value_ = "";
      displ_ = "";
      group_ = "";
      descr_ = "";
      suffix_ = "";
      key_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LightCandidateData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              value_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              displ_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              group_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              descr_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              suffix_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              key_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              complete_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.fernthedev.data.LightCandidate.internal_static_lightclient_packets_LightCandidateData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.fernthedev.data.LightCandidate.internal_static_lightclient_packets_LightCandidateData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.fernthedev.data.LightCandidate.LightCandidateData.class, com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder.class);
    }

    private int bitField0_;
    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>required string value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPL_FIELD_NUMBER = 2;
    private volatile java.lang.Object displ_;
    /**
     * <code>required string displ = 2;</code>
     */
    public boolean hasDispl() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string displ = 2;</code>
     */
    public java.lang.String getDispl() {
      java.lang.Object ref = displ_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displ_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string displ = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDisplBytes() {
      java.lang.Object ref = displ_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displ_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 3;
    private volatile java.lang.Object group_;
    /**
     * <code>required string group = 3;</code>
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string group = 3;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          group_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string group = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCR_FIELD_NUMBER = 4;
    private volatile java.lang.Object descr_;
    /**
     * <code>required string descr = 4;</code>
     */
    public boolean hasDescr() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string descr = 4;</code>
     */
    public java.lang.String getDescr() {
      java.lang.Object ref = descr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          descr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string descr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescrBytes() {
      java.lang.Object ref = descr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUFFIX_FIELD_NUMBER = 5;
    private volatile java.lang.Object suffix_;
    /**
     * <code>required string suffix = 5;</code>
     */
    public boolean hasSuffix() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string suffix = 5;</code>
     */
    public java.lang.String getSuffix() {
      java.lang.Object ref = suffix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          suffix_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string suffix = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSuffixBytes() {
      java.lang.Object ref = suffix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        suffix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 6;
    private volatile java.lang.Object key_;
    /**
     * <code>required string key = 6;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string key = 6;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 6;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPLETE_FIELD_NUMBER = 7;
    private boolean complete_;
    /**
     * <code>required bool complete = 7;</code>
     */
    public boolean hasComplete() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required bool complete = 7;</code>
     */
    public boolean getComplete() {
      return complete_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDispl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGroup()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSuffix()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasComplete()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, displ_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, group_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, descr_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, suffix_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, key_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBool(7, complete_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, displ_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, group_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, descr_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, suffix_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, key_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, complete_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.fernthedev.data.LightCandidate.LightCandidateData)) {
        return super.equals(obj);
      }
      com.github.fernthedev.data.LightCandidate.LightCandidateData other = (com.github.fernthedev.data.LightCandidate.LightCandidateData) obj;

      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (hasDispl() != other.hasDispl()) return false;
      if (hasDispl()) {
        if (!getDispl()
            .equals(other.getDispl())) return false;
      }
      if (hasGroup() != other.hasGroup()) return false;
      if (hasGroup()) {
        if (!getGroup()
            .equals(other.getGroup())) return false;
      }
      if (hasDescr() != other.hasDescr()) return false;
      if (hasDescr()) {
        if (!getDescr()
            .equals(other.getDescr())) return false;
      }
      if (hasSuffix() != other.hasSuffix()) return false;
      if (hasSuffix()) {
        if (!getSuffix()
            .equals(other.getSuffix())) return false;
      }
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasComplete() != other.hasComplete()) return false;
      if (hasComplete()) {
        if (getComplete()
            != other.getComplete()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasDispl()) {
        hash = (37 * hash) + DISPL_FIELD_NUMBER;
        hash = (53 * hash) + getDispl().hashCode();
      }
      if (hasGroup()) {
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
      }
      if (hasDescr()) {
        hash = (37 * hash) + DESCR_FIELD_NUMBER;
        hash = (53 * hash) + getDescr().hashCode();
      }
      if (hasSuffix()) {
        hash = (37 * hash) + SUFFIX_FIELD_NUMBER;
        hash = (53 * hash) + getSuffix().hashCode();
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasComplete()) {
        hash = (37 * hash) + COMPLETE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getComplete());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.fernthedev.data.LightCandidate.LightCandidateData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.fernthedev.data.LightCandidate.LightCandidateData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lightclient.packets.LightCandidateData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lightclient.packets.LightCandidateData)
        com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.fernthedev.data.LightCandidate.internal_static_lightclient_packets_LightCandidateData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.fernthedev.data.LightCandidate.internal_static_lightclient_packets_LightCandidateData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.fernthedev.data.LightCandidate.LightCandidateData.class, com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder.class);
      }

      // Construct using com.github.fernthedev.data.LightCandidate.LightCandidateData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        displ_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        descr_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        suffix_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        complete_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.fernthedev.data.LightCandidate.internal_static_lightclient_packets_LightCandidateData_descriptor;
      }

      @java.lang.Override
      public com.github.fernthedev.data.LightCandidate.LightCandidateData getDefaultInstanceForType() {
        return com.github.fernthedev.data.LightCandidate.LightCandidateData.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.fernthedev.data.LightCandidate.LightCandidateData build() {
        com.github.fernthedev.data.LightCandidate.LightCandidateData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.fernthedev.data.LightCandidate.LightCandidateData buildPartial() {
        com.github.fernthedev.data.LightCandidate.LightCandidateData result = new com.github.fernthedev.data.LightCandidate.LightCandidateData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.displ_ = displ_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.group_ = group_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.descr_ = descr_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.suffix_ = suffix_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.complete_ = complete_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.fernthedev.data.LightCandidate.LightCandidateData) {
          return mergeFrom((com.github.fernthedev.data.LightCandidate.LightCandidateData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.fernthedev.data.LightCandidate.LightCandidateData other) {
        if (other == com.github.fernthedev.data.LightCandidate.LightCandidateData.getDefaultInstance()) return this;
        if (other.hasValue()) {
          bitField0_ |= 0x00000001;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasDispl()) {
          bitField0_ |= 0x00000002;
          displ_ = other.displ_;
          onChanged();
        }
        if (other.hasGroup()) {
          bitField0_ |= 0x00000004;
          group_ = other.group_;
          onChanged();
        }
        if (other.hasDescr()) {
          bitField0_ |= 0x00000008;
          descr_ = other.descr_;
          onChanged();
        }
        if (other.hasSuffix()) {
          bitField0_ |= 0x00000010;
          suffix_ = other.suffix_;
          onChanged();
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000020;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasComplete()) {
          setComplete(other.getComplete());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasValue()) {
          return false;
        }
        if (!hasDispl()) {
          return false;
        }
        if (!hasGroup()) {
          return false;
        }
        if (!hasDescr()) {
          return false;
        }
        if (!hasSuffix()) {
          return false;
        }
        if (!hasKey()) {
          return false;
        }
        if (!hasComplete()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.fernthedev.data.LightCandidate.LightCandidateData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.fernthedev.data.LightCandidate.LightCandidateData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 1;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object displ_ = "";
      /**
       * <code>required string displ = 2;</code>
       */
      public boolean hasDispl() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string displ = 2;</code>
       */
      public java.lang.String getDispl() {
        java.lang.Object ref = displ_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            displ_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string displ = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDisplBytes() {
        java.lang.Object ref = displ_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displ_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string displ = 2;</code>
       */
      public Builder setDispl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        displ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string displ = 2;</code>
       */
      public Builder clearDispl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        displ_ = getDefaultInstance().getDispl();
        onChanged();
        return this;
      }
      /**
       * <code>required string displ = 2;</code>
       */
      public Builder setDisplBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        displ_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>required string group = 3;</code>
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string group = 3;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            group_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string group = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string group = 3;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string group = 3;</code>
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000004);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>required string group = 3;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object descr_ = "";
      /**
       * <code>required string descr = 4;</code>
       */
      public boolean hasDescr() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string descr = 4;</code>
       */
      public java.lang.String getDescr() {
        java.lang.Object ref = descr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            descr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string descr = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescrBytes() {
        java.lang.Object ref = descr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          descr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string descr = 4;</code>
       */
      public Builder setDescr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        descr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string descr = 4;</code>
       */
      public Builder clearDescr() {
        bitField0_ = (bitField0_ & ~0x00000008);
        descr_ = getDefaultInstance().getDescr();
        onChanged();
        return this;
      }
      /**
       * <code>required string descr = 4;</code>
       */
      public Builder setDescrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        descr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object suffix_ = "";
      /**
       * <code>required string suffix = 5;</code>
       */
      public boolean hasSuffix() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string suffix = 5;</code>
       */
      public java.lang.String getSuffix() {
        java.lang.Object ref = suffix_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            suffix_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string suffix = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSuffixBytes() {
        java.lang.Object ref = suffix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          suffix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string suffix = 5;</code>
       */
      public Builder setSuffix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        suffix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string suffix = 5;</code>
       */
      public Builder clearSuffix() {
        bitField0_ = (bitField0_ & ~0x00000010);
        suffix_ = getDefaultInstance().getSuffix();
        onChanged();
        return this;
      }
      /**
       * <code>required string suffix = 5;</code>
       */
      public Builder setSuffixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        suffix_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 6;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string key = 6;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 6;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 6;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 6;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 6;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        key_ = value;
        onChanged();
        return this;
      }

      private boolean complete_ ;
      /**
       * <code>required bool complete = 7;</code>
       */
      public boolean hasComplete() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required bool complete = 7;</code>
       */
      public boolean getComplete() {
        return complete_;
      }
      /**
       * <code>required bool complete = 7;</code>
       */
      public Builder setComplete(boolean value) {
        bitField0_ |= 0x00000040;
        complete_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool complete = 7;</code>
       */
      public Builder clearComplete() {
        bitField0_ = (bitField0_ & ~0x00000040);
        complete_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lightclient.packets.LightCandidateData)
    }

    // @@protoc_insertion_point(class_scope:lightclient.packets.LightCandidateData)
    private static final com.github.fernthedev.data.LightCandidate.LightCandidateData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.fernthedev.data.LightCandidate.LightCandidateData();
    }

    public static com.github.fernthedev.data.LightCandidate.LightCandidateData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LightCandidateData>
        PARSER = new com.google.protobuf.AbstractParser<LightCandidateData>() {
      @java.lang.Override
      public LightCandidateData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LightCandidateData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LightCandidateData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LightCandidateData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.fernthedev.data.LightCandidate.LightCandidateData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_LightCandidateData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_LightCandidateData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024LightCandidate.proto\022\023lightclient.pack" +
      "ets\"\177\n\022LightCandidateData\022\r\n\005value\030\001 \002(\t" +
      "\022\r\n\005displ\030\002 \002(\t\022\r\n\005group\030\003 \002(\t\022\r\n\005descr\030" +
      "\004 \002(\t\022\016\n\006suffix\030\005 \002(\t\022\013\n\003key\030\006 \002(\t\022\020\n\010co" +
      "mplete\030\007 \002(\010B\036\n\032com.github.fernthedev.da" +
      "taH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightclient_packets_LightCandidateData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightclient_packets_LightCandidateData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_LightCandidateData_descriptor,
        new java.lang.String[] { "Value", "Displ", "Group", "Descr", "Suffix", "Key", "Complete", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
