// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightCandidate.proto

package com.github.fernthedev.data;

public final class LightCandidate {
  private LightCandidate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_LightCandidateData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_LightCandidateData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024LightCandidate.proto\022\023lightclient.pack" +
      "ets\"\177\n\022LightCandidateData\022\r\n\005value\030\001 \001(\t" +
      "\022\r\n\005displ\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\022\r\n\005descr\030" +
      "\004 \001(\t\022\016\n\006suffix\030\005 \001(\t\022\013\n\003key\030\006 \001(\t\022\020\n\010co" +
      "mplete\030\007 \001(\010B \n\032com.github.fernthedev.da" +
      "taH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightclient_packets_LightCandidateData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightclient_packets_LightCandidateData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_LightCandidateData_descriptor,
        new java.lang.String[] { "Value", "Displ", "Group", "Descr", "Suffix", "Key", "Complete", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
