// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightCandidate.proto

package com.github.fernthedev.data;

public interface LightCandidateDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.LightCandidateData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string displ = 2;</code>
   */
  java.lang.String getDispl();
  /**
   * <code>string displ = 2;</code>
   */
  com.google.protobuf.ByteString
      getDisplBytes();

  /**
   * <code>string group = 3;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string descr = 4;</code>
   */
  java.lang.String getDescr();
  /**
   * <code>string descr = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescrBytes();

  /**
   * <code>string suffix = 5;</code>
   */
  java.lang.String getSuffix();
  /**
   * <code>string suffix = 5;</code>
   */
  com.google.protobuf.ByteString
      getSuffixBytes();

  /**
   * <code>string key = 6;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 6;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>bool complete = 7;</code>
   */
  boolean getComplete();
}
