// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

/**
 * Protobuf type {@code lightclient.packets.AutoCompletePacket}
 */
public  final class AutoCompletePacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lightclient.packets.AutoCompletePacket)
    AutoCompletePacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AutoCompletePacket.newBuilder() to construct.
  private AutoCompletePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AutoCompletePacket() {
    candidateList_ = java.util.Collections.emptyList();
    wordsListJson_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AutoCompletePacket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              candidateList_ = new java.util.ArrayList<com.github.fernthedev.data.LightCandidate.LightCandidateData>();
              mutable_bitField0_ |= 0x00000001;
            }
            candidateList_.add(
                input.readMessage(com.github.fernthedev.data.LightCandidate.LightCandidateData.PARSER, extensionRegistry));
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              wordsListJson_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            wordsListJson_.add(bs);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        candidateList_ = java.util.Collections.unmodifiableList(candidateList_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        wordsListJson_ = wordsListJson_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.fernthedev.packets.PacketOuterClass.internal_static_lightclient_packets_AutoCompletePacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.fernthedev.packets.PacketOuterClass.internal_static_lightclient_packets_AutoCompletePacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.fernthedev.packets.AutoCompletePacket.class, com.github.fernthedev.packets.AutoCompletePacket.Builder.class);
  }

  public static final int CANDIDATELIST_FIELD_NUMBER = 2;
  private java.util.List<com.github.fernthedev.data.LightCandidate.LightCandidateData> candidateList_;
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  public java.util.List<com.github.fernthedev.data.LightCandidate.LightCandidateData> getCandidateListList() {
    return candidateList_;
  }
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  public java.util.List<? extends com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder> 
      getCandidateListOrBuilderList() {
    return candidateList_;
  }
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  public int getCandidateListCount() {
    return candidateList_.size();
  }
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  public com.github.fernthedev.data.LightCandidate.LightCandidateData getCandidateList(int index) {
    return candidateList_.get(index);
  }
  /**
   * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
   */
  public com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder getCandidateListOrBuilder(
      int index) {
    return candidateList_.get(index);
  }

  public static final int WORDSLISTJSON_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList wordsListJson_;
  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getWordsListJsonList() {
    return wordsListJson_;
  }
  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  public int getWordsListJsonCount() {
    return wordsListJson_.size();
  }
  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  public java.lang.String getWordsListJson(int index) {
    return wordsListJson_.get(index);
  }
  /**
   * <code>repeated string wordsListJson = 3;</code>
   */
  public com.google.protobuf.ByteString
      getWordsListJsonBytes(int index) {
    return wordsListJson_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getCandidateListCount(); i++) {
      if (!getCandidateList(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < candidateList_.size(); i++) {
      output.writeMessage(2, candidateList_.get(i));
    }
    for (int i = 0; i < wordsListJson_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, wordsListJson_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < candidateList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, candidateList_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < wordsListJson_.size(); i++) {
        dataSize += computeStringSizeNoTag(wordsListJson_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getWordsListJsonList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.fernthedev.packets.AutoCompletePacket)) {
      return super.equals(obj);
    }
    com.github.fernthedev.packets.AutoCompletePacket other = (com.github.fernthedev.packets.AutoCompletePacket) obj;

    if (!getCandidateListList()
        .equals(other.getCandidateListList())) return false;
    if (!getWordsListJsonList()
        .equals(other.getWordsListJsonList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCandidateListCount() > 0) {
      hash = (37 * hash) + CANDIDATELIST_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateListList().hashCode();
    }
    if (getWordsListJsonCount() > 0) {
      hash = (37 * hash) + WORDSLISTJSON_FIELD_NUMBER;
      hash = (53 * hash) + getWordsListJsonList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.fernthedev.packets.AutoCompletePacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.fernthedev.packets.AutoCompletePacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lightclient.packets.AutoCompletePacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lightclient.packets.AutoCompletePacket)
      com.github.fernthedev.packets.AutoCompletePacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.fernthedev.packets.PacketOuterClass.internal_static_lightclient_packets_AutoCompletePacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.fernthedev.packets.PacketOuterClass.internal_static_lightclient_packets_AutoCompletePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.fernthedev.packets.AutoCompletePacket.class, com.github.fernthedev.packets.AutoCompletePacket.Builder.class);
    }

    // Construct using com.github.fernthedev.packets.AutoCompletePacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCandidateListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (candidateListBuilder_ == null) {
        candidateList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        candidateListBuilder_.clear();
      }
      wordsListJson_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.fernthedev.packets.PacketOuterClass.internal_static_lightclient_packets_AutoCompletePacket_descriptor;
    }

    @java.lang.Override
    public com.github.fernthedev.packets.AutoCompletePacket getDefaultInstanceForType() {
      return com.github.fernthedev.packets.AutoCompletePacket.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.fernthedev.packets.AutoCompletePacket build() {
      com.github.fernthedev.packets.AutoCompletePacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.fernthedev.packets.AutoCompletePacket buildPartial() {
      com.github.fernthedev.packets.AutoCompletePacket result = new com.github.fernthedev.packets.AutoCompletePacket(this);
      int from_bitField0_ = bitField0_;
      if (candidateListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          candidateList_ = java.util.Collections.unmodifiableList(candidateList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.candidateList_ = candidateList_;
      } else {
        result.candidateList_ = candidateListBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        wordsListJson_ = wordsListJson_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.wordsListJson_ = wordsListJson_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.fernthedev.packets.AutoCompletePacket) {
        return mergeFrom((com.github.fernthedev.packets.AutoCompletePacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.fernthedev.packets.AutoCompletePacket other) {
      if (other == com.github.fernthedev.packets.AutoCompletePacket.getDefaultInstance()) return this;
      if (candidateListBuilder_ == null) {
        if (!other.candidateList_.isEmpty()) {
          if (candidateList_.isEmpty()) {
            candidateList_ = other.candidateList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCandidateListIsMutable();
            candidateList_.addAll(other.candidateList_);
          }
          onChanged();
        }
      } else {
        if (!other.candidateList_.isEmpty()) {
          if (candidateListBuilder_.isEmpty()) {
            candidateListBuilder_.dispose();
            candidateListBuilder_ = null;
            candidateList_ = other.candidateList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            candidateListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCandidateListFieldBuilder() : null;
          } else {
            candidateListBuilder_.addAllMessages(other.candidateList_);
          }
        }
      }
      if (!other.wordsListJson_.isEmpty()) {
        if (wordsListJson_.isEmpty()) {
          wordsListJson_ = other.wordsListJson_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureWordsListJsonIsMutable();
          wordsListJson_.addAll(other.wordsListJson_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getCandidateListCount(); i++) {
        if (!getCandidateList(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.fernthedev.packets.AutoCompletePacket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.fernthedev.packets.AutoCompletePacket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.fernthedev.data.LightCandidate.LightCandidateData> candidateList_ =
      java.util.Collections.emptyList();
    private void ensureCandidateListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        candidateList_ = new java.util.ArrayList<com.github.fernthedev.data.LightCandidate.LightCandidateData>(candidateList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.fernthedev.data.LightCandidate.LightCandidateData, com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder, com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder> candidateListBuilder_;

    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public java.util.List<com.github.fernthedev.data.LightCandidate.LightCandidateData> getCandidateListList() {
      if (candidateListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(candidateList_);
      } else {
        return candidateListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public int getCandidateListCount() {
      if (candidateListBuilder_ == null) {
        return candidateList_.size();
      } else {
        return candidateListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public com.github.fernthedev.data.LightCandidate.LightCandidateData getCandidateList(int index) {
      if (candidateListBuilder_ == null) {
        return candidateList_.get(index);
      } else {
        return candidateListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder setCandidateList(
        int index, com.github.fernthedev.data.LightCandidate.LightCandidateData value) {
      if (candidateListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateListIsMutable();
        candidateList_.set(index, value);
        onChanged();
      } else {
        candidateListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder setCandidateList(
        int index, com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder builderForValue) {
      if (candidateListBuilder_ == null) {
        ensureCandidateListIsMutable();
        candidateList_.set(index, builderForValue.build());
        onChanged();
      } else {
        candidateListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder addCandidateList(com.github.fernthedev.data.LightCandidate.LightCandidateData value) {
      if (candidateListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateListIsMutable();
        candidateList_.add(value);
        onChanged();
      } else {
        candidateListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder addCandidateList(
        int index, com.github.fernthedev.data.LightCandidate.LightCandidateData value) {
      if (candidateListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCandidateListIsMutable();
        candidateList_.add(index, value);
        onChanged();
      } else {
        candidateListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder addCandidateList(
        com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder builderForValue) {
      if (candidateListBuilder_ == null) {
        ensureCandidateListIsMutable();
        candidateList_.add(builderForValue.build());
        onChanged();
      } else {
        candidateListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder addCandidateList(
        int index, com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder builderForValue) {
      if (candidateListBuilder_ == null) {
        ensureCandidateListIsMutable();
        candidateList_.add(index, builderForValue.build());
        onChanged();
      } else {
        candidateListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder addAllCandidateList(
        java.lang.Iterable<? extends com.github.fernthedev.data.LightCandidate.LightCandidateData> values) {
      if (candidateListBuilder_ == null) {
        ensureCandidateListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, candidateList_);
        onChanged();
      } else {
        candidateListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder clearCandidateList() {
      if (candidateListBuilder_ == null) {
        candidateList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        candidateListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public Builder removeCandidateList(int index) {
      if (candidateListBuilder_ == null) {
        ensureCandidateListIsMutable();
        candidateList_.remove(index);
        onChanged();
      } else {
        candidateListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder getCandidateListBuilder(
        int index) {
      return getCandidateListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder getCandidateListOrBuilder(
        int index) {
      if (candidateListBuilder_ == null) {
        return candidateList_.get(index);  } else {
        return candidateListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public java.util.List<? extends com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder> 
         getCandidateListOrBuilderList() {
      if (candidateListBuilder_ != null) {
        return candidateListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(candidateList_);
      }
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder addCandidateListBuilder() {
      return getCandidateListFieldBuilder().addBuilder(
          com.github.fernthedev.data.LightCandidate.LightCandidateData.getDefaultInstance());
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder addCandidateListBuilder(
        int index) {
      return getCandidateListFieldBuilder().addBuilder(
          index, com.github.fernthedev.data.LightCandidate.LightCandidateData.getDefaultInstance());
    }
    /**
     * <code>repeated .lightclient.packets.LightCandidateData candidateList = 2;</code>
     */
    public java.util.List<com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder> 
         getCandidateListBuilderList() {
      return getCandidateListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.fernthedev.data.LightCandidate.LightCandidateData, com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder, com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder> 
        getCandidateListFieldBuilder() {
      if (candidateListBuilder_ == null) {
        candidateListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.fernthedev.data.LightCandidate.LightCandidateData, com.github.fernthedev.data.LightCandidate.LightCandidateData.Builder, com.github.fernthedev.data.LightCandidate.LightCandidateDataOrBuilder>(
                candidateList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        candidateList_ = null;
      }
      return candidateListBuilder_;
    }

    private com.google.protobuf.LazyStringList wordsListJson_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureWordsListJsonIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        wordsListJson_ = new com.google.protobuf.LazyStringArrayList(wordsListJson_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getWordsListJsonList() {
      return wordsListJson_.getUnmodifiableView();
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public int getWordsListJsonCount() {
      return wordsListJson_.size();
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public java.lang.String getWordsListJson(int index) {
      return wordsListJson_.get(index);
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWordsListJsonBytes(int index) {
      return wordsListJson_.getByteString(index);
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public Builder setWordsListJson(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsListJsonIsMutable();
      wordsListJson_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public Builder addWordsListJson(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsListJsonIsMutable();
      wordsListJson_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public Builder addAllWordsListJson(
        java.lang.Iterable<java.lang.String> values) {
      ensureWordsListJsonIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, wordsListJson_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public Builder clearWordsListJson() {
      wordsListJson_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string wordsListJson = 3;</code>
     */
    public Builder addWordsListJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsListJsonIsMutable();
      wordsListJson_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lightclient.packets.AutoCompletePacket)
  }

  // @@protoc_insertion_point(class_scope:lightclient.packets.AutoCompletePacket)
  private static final com.github.fernthedev.packets.AutoCompletePacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.fernthedev.packets.AutoCompletePacket();
  }

  public static com.github.fernthedev.packets.AutoCompletePacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AutoCompletePacket>
      PARSER = new com.google.protobuf.AbstractParser<AutoCompletePacket>() {
    @java.lang.Override
    public AutoCompletePacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AutoCompletePacket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AutoCompletePacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AutoCompletePacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.fernthedev.packets.AutoCompletePacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  public static final int PACKETTYPE_FIELD_NUMBER = 101;
  /**
   * <code>extend .lightclient.packets.Packet { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.github.fernthedev.packets.Packet,
      com.github.fernthedev.packets.Packet> packetType = com.google.protobuf.GeneratedMessage
          .newMessageScopedGeneratedExtension(
        com.github.fernthedev.packets.AutoCompletePacket.getDefaultInstance(),
        0,
        com.github.fernthedev.packets.Packet.class,
        com.github.fernthedev.packets.Packet.getDefaultInstance());
}

