// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface ConnectedPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.ConnectedPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 4;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string os = 5;</code>
   */
  boolean hasOs();
  /**
   * <code>required string os = 5;</code>
   */
  java.lang.String getOs();
  /**
   * <code>required string os = 5;</code>
   */
  com.google.protobuf.ByteString
      getOsBytes();

  /**
   * <code>required string uuid = 6;</code>
   */
  boolean hasUuid();
  /**
   * <code>required string uuid = 6;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>required string uuid = 6;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>required string privateKey = 7;</code>
   */
  boolean hasPrivateKey();
  /**
   * <code>required string privateKey = 7;</code>
   */
  java.lang.String getPrivateKey();
  /**
   * <code>required string privateKey = 7;</code>
   */
  com.google.protobuf.ByteString
      getPrivateKeyBytes();
}
