// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface IllegalConnectionPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.IllegalConnectionPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string message = 8;</code>
   */
  boolean hasMessage();
  /**
   * <code>required string message = 8;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>required string message = 8;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
