// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightclient.packets.Packet)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<Packet> {
}
