// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

public final class PacketOuterClass {
  private PacketOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.github.fernthedev.packets.MessagePacket.packetType);
    registry.add(com.github.fernthedev.packets.AutoCompletePacket.packetType);
    registry.add(com.github.fernthedev.packets.ConnectedPacket.packetType);
    registry.add(com.github.fernthedev.packets.IllegalConnectionPacket.packetType);
    registry.add(com.github.fernthedev.packets.RequestInfoPacket.packetType);
    registry.add(com.github.fernthedev.packets.SelfMessagePacket.packetType);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_Packet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_MessagePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_MessagePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_AutoCompletePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_AutoCompletePacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_ConnectedPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_ConnectedPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_IllegalConnectionPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_IllegalConnectionPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_RequestInfoPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_RequestInfoPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightclient_packets_SelfMessagePacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightclient_packets_SelfMessagePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Packet.proto\022\023lightclient.packets\032\024Lig" +
      "htCandidate.proto\"\022\n\006Packet*\010\010\001\020\200\200\200\200\002\"n\n" +
      "\rMessagePacket\022\017\n\007message\030\001 \002(\t2L\n\npacke" +
      "tType\022\033.lightclient.packets.Packet\030d \001(\013" +
      "2\033.lightclient.packets.Packet\"\271\001\n\022AutoCo" +
      "mpletePacket\022>\n\rcandidateList\030\002 \003(\0132\'.li" +
      "ghtclient.packets.LightCandidateData\022\025\n\r" +
      "wordsListJson\030\003 \003(\t2L\n\npacketType\022\033.ligh" +
      "tclient.packets.Packet\030e \001(\0132\033.lightclie" +
      "nt.packets.Packet\"\233\001\n\017ConnectedPacket\022\014\n" +
      "\004name\030\004 \002(\t\022\n\n\002os\030\005 \002(\t\022\014\n\004uuid\030\006 \002(\t\022\022\n" +
      "\nprivateKey\030\007 \002(\t2L\n\npacketType\022\033.lightc" +
      "lient.packets.Packet\030f \001(\0132\033.lightclient" +
      ".packets.Packet\"x\n\027IllegalConnectionPack" +
      "et\022\017\n\007message\030\010 \002(\t2L\n\npacketType\022\033.ligh" +
      "tclient.packets.Packet\030g \001(\0132\033.lightclie" +
      "nt.packets.Packet\"x\n\021RequestInfoPacket\022\025" +
      "\n\rencryptionKey\030\t \002(\t2L\n\npacketType\022\033.li" +
      "ghtclient.packets.Packet\030h \001(\0132\033.lightcl" +
      "ient.packets.Packet\"\234\001\n\021SelfMessagePacke" +
      "t\0229\n\013messageType\030\n \002(\0162$.lightclient.pac" +
      "kets.SelfMessageType2L\n\npacketType\022\033.lig" +
      "htclient.packets.Packet\030i \001(\0132\033.lightcli" +
      "ent.packets.Packet*\307\001\n\017SelfMessageType\022\026" +
      "\n\022FillPasswordPacket\020\000\022\036\n\032LostServerConn" +
      "ectionPacket\020\001\022\022\n\016RegisterPacket\020\002\022\036\n\032Ti" +
      "medOutRegistrationPacket\020\003\022\016\n\nPongPacket" +
      "\020\004\022\017\n\013PingReceive\020\005\022\016\n\nPingPacket\020\006\022\027\n\023A" +
      "uthenticateMessage\020\007B#\n\035com.github.fernt" +
      "hedev.packetsH\001P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.fernthedev.data.LightCandidate.getDescriptor(),
        }, assigner);
    internal_static_lightclient_packets_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightclient_packets_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_Packet_descriptor,
        new java.lang.String[] { });
    internal_static_lightclient_packets_MessagePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightclient_packets_MessagePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_MessagePacket_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_lightclient_packets_AutoCompletePacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightclient_packets_AutoCompletePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_AutoCompletePacket_descriptor,
        new java.lang.String[] { "CandidateList", "WordsListJson", });
    internal_static_lightclient_packets_ConnectedPacket_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lightclient_packets_ConnectedPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_ConnectedPacket_descriptor,
        new java.lang.String[] { "Name", "Os", "Uuid", "PrivateKey", });
    internal_static_lightclient_packets_IllegalConnectionPacket_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lightclient_packets_IllegalConnectionPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_IllegalConnectionPacket_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_lightclient_packets_RequestInfoPacket_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lightclient_packets_RequestInfoPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_RequestInfoPacket_descriptor,
        new java.lang.String[] { "EncryptionKey", });
    internal_static_lightclient_packets_SelfMessagePacket_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lightclient_packets_SelfMessagePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightclient_packets_SelfMessagePacket_descriptor,
        new java.lang.String[] { "MessageType", });
    com.github.fernthedev.data.LightCandidate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
