// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.github.fernthedev.packets;

/**
 * Protobuf enum {@code lightclient.packets.SelfMessageType}
 */
public enum SelfMessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FillPasswordPacket = 0;</code>
   */
  FillPasswordPacket(0),
  /**
   * <code>LostServerConnectionPacket = 1;</code>
   */
  LostServerConnectionPacket(1),
  /**
   * <code>RegisterPacket = 2;</code>
   */
  RegisterPacket(2),
  /**
   * <code>TimedOutRegistrationPacket = 3;</code>
   */
  TimedOutRegistrationPacket(3),
  /**
   * <code>PongPacket = 4;</code>
   */
  PongPacket(4),
  /**
   * <code>PingReceive = 5;</code>
   */
  PingReceive(5),
  /**
   * <code>PingPacket = 6;</code>
   */
  PingPacket(6),
  /**
   * <code>AuthenticateMessage = 7;</code>
   */
  AuthenticateMessage(7),
  ;

  /**
   * <code>FillPasswordPacket = 0;</code>
   */
  public static final int FillPasswordPacket_VALUE = 0;
  /**
   * <code>LostServerConnectionPacket = 1;</code>
   */
  public static final int LostServerConnectionPacket_VALUE = 1;
  /**
   * <code>RegisterPacket = 2;</code>
   */
  public static final int RegisterPacket_VALUE = 2;
  /**
   * <code>TimedOutRegistrationPacket = 3;</code>
   */
  public static final int TimedOutRegistrationPacket_VALUE = 3;
  /**
   * <code>PongPacket = 4;</code>
   */
  public static final int PongPacket_VALUE = 4;
  /**
   * <code>PingReceive = 5;</code>
   */
  public static final int PingReceive_VALUE = 5;
  /**
   * <code>PingPacket = 6;</code>
   */
  public static final int PingPacket_VALUE = 6;
  /**
   * <code>AuthenticateMessage = 7;</code>
   */
  public static final int AuthenticateMessage_VALUE = 7;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SelfMessageType valueOf(int value) {
    return forNumber(value);
  }

  public static SelfMessageType forNumber(int value) {
    switch (value) {
      case 0: return FillPasswordPacket;
      case 1: return LostServerConnectionPacket;
      case 2: return RegisterPacket;
      case 3: return TimedOutRegistrationPacket;
      case 4: return PongPacket;
      case 5: return PingReceive;
      case 6: return PingPacket;
      case 7: return AuthenticateMessage;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SelfMessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SelfMessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SelfMessageType>() {
          public SelfMessageType findValueByNumber(int number) {
            return SelfMessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.fernthedev.packets.PacketOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final SelfMessageType[] VALUES = values();

  public static SelfMessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SelfMessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:lightclient.packets.SelfMessageType)
}

