name: JavaCI

on:
  push:
    paths:
      - "java/**"
      - "java/*"
      - "java/"
  release:
    types: # This configuration does not affect the page_build event above
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: cd java && chmod +x ./gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: cd java && ./gradlew clean build
      - name: Upload server artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Server Jar Files
          # Directory containing files to upload
          path: ./java/terminal/terminal-server/build/libs/*all.jar
      - name: Upload client artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Client Jar Files
          # Directory containing files to upload
          path: ./java/terminal/terminal-client/build/libs/*all.jar
